default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV["DATABASE_URL"] if ENV["DATABASE_URL"] %>
  variables:
    statement_timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "ai_sales_agent_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_TEST_DB", "ai_sales_agent_test") %>

staging:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "ai_sales_agent_staging") %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "ai_sales_agent_production") %>
