source "https://rubygems.org"

ruby "3.3.9"

gem "rails", "~> 7.1.3"
gem "pg", "~> 1.6"
gem "puma", "~> 6.4"
gem "rack-cors"
gem "rack-attack", "~> 6.7"
gem "redis", "~> 5.2"
gem "sidekiq", "~> 7.2"
gem "faraday", "~> 2.10"
gem "dry-struct", "~> 1.6"
gem "dotenv-rails", groups: [:development, :test]
gem "devise", "~> 4.9"
gem "devise-jwt", "~> 0.11"
gem "pundit", "~> 2.3"
gem "pagy", "~> 6.4"

# Logging & instrumentation
gem "lograge", "~> 0.12"

group :development, :test do
  gem "pry-rails"
  gem "rspec-rails", "~> 6.1"
  gem "factory_bot_rails"
  gem "faker"
  gem "shoulda-matchers", "~> 6.4"
  gem "simplecov", require: false
  gem "database_cleaner-active_record"
  gem "rspec-sidekiq"
  gem "webmock"
end

group :development do
  gem "rubocop", require: false
  gem "rubocop-performance", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
  gem "solargraph", require: false
  gem "brakeman", require: false
  gem "bundler-audit", require: false
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false
