source "https://rubygems.org"

ruby "3.3.9"

gem "rails", "~> 7.1.3"
gem "pg", "~> 1.6"
gem "puma", "~> 6.4"
gem "sidekiq", "~> 7.2"
gem "redis", "~> 5.2"
gem "dotenv-rails", groups: [:development, :test]
gem "lograge", "~> 0.12"
gem "mail", "~> 2.8"
gem "premailer-rails"
gem "rack-cors"

group :development, :test do
  gem "rspec-rails", "~> 6.1"
  gem "factory_bot_rails"
  gem "faker"
  gem "shoulda-matchers", "~> 6.4"
  gem "simplecov", require: false
  gem "database_cleaner-active_record"
  gem "rspec-sidekiq"
end

group :development do
  gem "letter_opener_web", "~> 2.0"
  gem "rubocop", require: false
  gem "rubocop-performance", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false
